spring:
  # redis相关配置
  redis:
    # 指定Redis库（默认为0）
    database: 1
    # Redis 地址
    host: localhost
    # Redis 端口
    port: 6379
    # Redis 密码，默认为空
    password:
    # Redis 连接超时时间（毫秒）
    timeout: 2000ms
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接数
        max-idle: 8
        # 连接池中的最小空闲连接数
        min-idle: 2
  rabbitmq:
    host: localhsot
    # rabbit 默认端口5672
    port: 5672
    # rabbit 默认用户名、密码均为guest
    username: guest
    password: guest
    #  消息发送到交换机确认机制,是否确认回调
    publisher-confirms: true
    publisher-returns: true
  # http相关配置
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
#  jackson:
#    time-zone: GTM+8
#    date-format: yyyy-MM-dd HH:mm:ss
# mybatis 设置
mybatis:
  mapper-locations: classpath*:/mapper/**.xml   #把xml文件放在com.XX.mapper.*中可能会出现找到的问题，这里把他放在resource下的mapper中
  #  typeAliasesPackage: com.gimiii.server.mall.model  #这里是实体类的位置 多个package用逗号或者分号分隔
  configuration:
    lazyLoadingEnabled: false #延时加载的开关
    map-underscore-to-camel-case: true
    cache-enabled: false
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
    key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
#安全头设置
cloud-Authorization: mdd-cloud-authorization-dev

#okhttp 相关配置
okhttp:
  readTimeout: 600  #单位S
  connectTimeout: 600 #单位S
  writeTimeout: 1200 #单位S
  maxIdleConnections: 300
  keepAliveDuration: 600 #单位S